"""Active theory API for the submission supplement."""

from .critical_context import CriticalContextComparison, ZeroCrossing, compare_critical_contexts, zero_crossing
from .critical_definition_concordance import (
    CrossingBracket,
    DefinitionConcordance,
    analyze_definitions,
    compare_definition_brackets,
    crossing_bracket,
)
from .criticality import (
    CriticalityMap,
    architecture_margin,
    classify_architecture_margin,
    classify_empirical_release,
    critical_coupling,
    critical_cost,
    critical_decoupling,
    critical_optimum_distance,
    critical_shared_load,
    criticality_map,
    cross_world_equivalence_statement,
    empirical_release_margin,
    shared_conflict_load,
)
from .functional_weight_criticality import (
    FunctionalWeightCriticality,
    asymptotic_recoverable_loss,
    critical_function2_weight,
    monotonicity_log_derivative,
    recoverable_loss_at_function2_weight,
)
from .differentiation import (
    ArchitectureComparison,
    DifferentiatedAxisOptimum,
    SharedAxisOptimum,
    compare_architectures,
    decoupling_fraction,
    differentiated_axis_optimum,
    differentiation_threshold,
    shared_axis_optimum,
)
from .differentiation_robustness import (
    PowerArchitectureComparison,
    PowerDifferentiatedOptimum,
    PowerSharedOptimum,
    compare_power_architectures,
    differentiated_power_optimum,
    shared_power_optimum,
)
from .identification import (
    CrossedIdentificationResult,
    IdentificationAssumptions,
    JointCostAssayResult,
    JointCostComparison,
    compare_joint_cost,
    context_delta_ad,
    delta_ad,
    estimate_joint_cost_assay,
    identify_crossed_design,
)
from .model import Architecture, FitnessBreakdown, InteractionRegime, ModelParameters, fitness
from .partial_identification import (
    EscapeClaimHierarchy,
    Interval,
    classify_constraint_release,
    classify_escape_claim_hierarchy,
    classify_escape_criterion,
    classify_interaction_relief,
    classify_strict_reversal,
    partial_identification_from_total,
)
from .sign_criterion import (
    OrientedSignCriterion,
    RegimeDerivativeBalance,
    RegimeScaledCriterion,
    SeparableLocalRegimeCriterion,
)

__all__ = [
    "Architecture",
    "FitnessBreakdown",
    "InteractionRegime",
    "ModelParameters",
    "fitness",
    "SharedAxisOptimum",
    "DifferentiatedAxisOptimum",
    "ArchitectureComparison",
    "shared_axis_optimum",
    "decoupling_fraction",
    "differentiated_axis_optimum",
    "differentiation_threshold",
    "compare_architectures",
    "PowerSharedOptimum",
    "PowerDifferentiatedOptimum",
    "PowerArchitectureComparison",
    "shared_power_optimum",
    "differentiated_power_optimum",
    "compare_power_architectures",
    "CriticalityMap",
    "architecture_margin",
    "classify_architecture_margin",
    "classify_empirical_release",
    "critical_coupling",
    "critical_cost",
    "critical_decoupling",
    "critical_optimum_distance",
    "critical_shared_load",
    "criticality_map",
    "cross_world_equivalence_statement",
    "empirical_release_margin",
    "shared_conflict_load",
    "FunctionalWeightCriticality",
    "asymptotic_recoverable_loss",
    "critical_function2_weight",
    "monotonicity_log_derivative",
    "recoverable_loss_at_function2_weight",
    "CrossingBracket",
    "DefinitionConcordance",
    "crossing_bracket",
    "compare_definition_brackets",
    "analyze_definitions",
    "ZeroCrossing",
    "CriticalContextComparison",
    "zero_crossing",
    "compare_critical_contexts",
    "OrientedSignCriterion",
    "RegimeDerivativeBalance",
    "RegimeScaledCriterion",
    "SeparableLocalRegimeCriterion",
    "CrossedIdentificationResult",
    "IdentificationAssumptions",
    "JointCostAssayResult",
    "JointCostComparison",
    "compare_joint_cost",
    "context_delta_ad",
    "delta_ad",
    "estimate_joint_cost_assay",
    "identify_crossed_design",
    "EscapeClaimHierarchy",
    "Interval",
    "classify_constraint_release",
    "classify_escape_claim_hierarchy",
    "classify_escape_criterion",
    "classify_interaction_relief",
    "classify_strict_reversal",
    "partial_identification_from_total",
]
