"""Minimal dynamic persistence model for the balance-domain incubator.

This model is deliberately separate from BITA's static architecture cost.  It
adds explicit one-time switching costs and an effective environmental
persistence horizon.  It is an incubator result, not part of the canonical
submission model.
"""

from __future__ import annotations

from dataclasses import dataclass
import math


@dataclass(frozen=True)
class PersistenceBand:
    reverse_threshold_phi: float
    forward_threshold_phi: float
    width_phi: float
    switching_cost_shared_to_differentiated: float
    switching_cost_differentiated_to_shared: float
    horizon: float


def persistence_band(
    *,
    switching_cost_shared_to_differentiated: float,
    switching_cost_differentiated_to_shared: float,
    horizon: float,
) -> PersistenceBand:
    """Return the exact finite-horizon architecture persistence band.

    Let ``phi = W_D-W_S`` be the *per-horizon-unit* differentiated-minus-shared
    fitness advantage after ordinary maintenance costs have already been
    included.  Over a context that persists for ``T`` units:

    - an organism currently in the shared architecture switches to the
      differentiated architecture only if ``T*phi > C_SD``;
    - an organism currently in the differentiated architecture switches back
      only if ``-T*phi > C_DS``.

    Hence both current architectures persist without switching when

        -C_DS/T <= phi <= C_SD/T.

    This is a true history-dependent band generated by explicit switching
    costs; it must not be inferred from the static BITA cost ``K`` alone.
    """

    c_sd = float(switching_cost_shared_to_differentiated)
    c_ds = float(switching_cost_differentiated_to_shared)
    horizon = float(horizon)
    for value, name in ((c_sd, "switching_cost_shared_to_differentiated"), (c_ds, "switching_cost_differentiated_to_shared"), (horizon, "horizon")):
        if not math.isfinite(value):
            raise ValueError(f"{name} must be finite")
    if c_sd < 0 or c_ds < 0:
        raise ValueError("switching costs must be non-negative")
    if horizon <= 0:
        raise ValueError("horizon must be positive")

    reverse = -c_ds / horizon
    forward = c_sd / horizon
    return PersistenceBand(
        reverse_threshold_phi=reverse,
        forward_threshold_phi=forward,
        width_phi=forward - reverse,
        switching_cost_shared_to_differentiated=c_sd,
        switching_cost_differentiated_to_shared=c_ds,
        horizon=horizon,
    )


def architecture_action(
    *,
    phi: float,
    current_architecture: str,
    switching_cost_shared_to_differentiated: float,
    switching_cost_differentiated_to_shared: float,
    horizon: float,
    tolerance: float = 1e-12,
) -> str:
    """Return ``stay`` or ``switch`` under the registered finite-horizon rule."""

    phi = float(phi)
    if not math.isfinite(phi):
        raise ValueError("phi must be finite")
    band = persistence_band(
        switching_cost_shared_to_differentiated=switching_cost_shared_to_differentiated,
        switching_cost_differentiated_to_shared=switching_cost_differentiated_to_shared,
        horizon=horizon,
    )
    if current_architecture == "shared":
        return "switch" if phi > band.forward_threshold_phi + tolerance else "stay"
    if current_architecture == "differentiated":
        return "switch" if phi < band.reverse_threshold_phi - tolerance else "stay"
    raise ValueError("current_architecture must be 'shared' or 'differentiated'")


def local_environmental_hysteresis_width(
    *,
    phi_slope_at_static_boundary: float,
    switching_cost_shared_to_differentiated: float,
    switching_cost_differentiated_to_shared: float,
    horizon: float,
) -> float:
    """First-order environmental width of the hysteresis band.

    If ``phi(e)`` is locally monotone around the static ``phi=0`` boundary,
    linearization gives

        Delta e ~= (C_SD + C_DS) / (T * |d phi/de|).

    The function fails closed at a zero or non-finite slope.
    """

    slope = float(phi_slope_at_static_boundary)
    if not math.isfinite(slope) or abs(slope) <= 0:
        raise ValueError("phi_slope_at_static_boundary must be finite and non-zero")
    band = persistence_band(
        switching_cost_shared_to_differentiated=switching_cost_shared_to_differentiated,
        switching_cost_differentiated_to_shared=switching_cost_differentiated_to_shared,
        horizon=horizon,
    )
    return band.width_phi / abs(slope)
