"""A minimal qualitative fitness-score corollary for one focal floral trait pair.

The model maps a phenotype ``(A, D, R)`` and an exogenous interaction regime
``(P, H)`` to a decomposed score.  It is used for local mixed-partial and
sensitivity calculations, not for estimating absolute fitness or an evolutionary
endpoint in a particular species.

A = one declared focal floral attraction trait
D = one declared flower-specific barrier/defence trait
R = reproductive-assurance investment retained as an auxiliary moderator
P = exogenous reference intensity of pollinator service
H = exogenous reference intensity of floral-antagonist pressure

``A`` and ``D`` are not omnibus trait classes.  A concrete application must choose
one biologically defined pair and its measurement scale.  ``D`` is defined by its
flower-specific antagonist-reduction role; any reduction in pollinator return is a
possible collateral effect of that same focal trait, not a separate definition of
``D``.

The core A--D result concerns the mixed partial of the declared score surface.
Terms that do not depend jointly on A and D can change total score or single-trait
marginal effects without changing that mixed partial.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import exp


def _unit_interval(value: float, name: str) -> None:
    if not 0.0 <= value <= 1.0:
        raise ValueError(f"{name} must lie in [0, 1]")


@dataclass(frozen=True)
class Architecture:
    """Scaled values of the focal attraction, defence/barrier, and assurance traits."""

    attraction: float
    defence: float
    assurance: float

    def __post_init__(self) -> None:
        _unit_interval(self.attraction, "attraction")
        _unit_interval(self.defence, "defence")
        _unit_interval(self.assurance, "assurance")


@dataclass(frozen=True)
class InteractionRegime:
    """Scaled exogenous reference intensities for the two interaction environments."""

    pollinator_service: float
    floral_damage_pressure: float

    def __post_init__(self) -> None:
        _unit_interval(self.pollinator_service, "pollinator_service")
        _unit_interval(self.floral_damage_pressure, "floral_damage_pressure")


@dataclass(frozen=True)
class ModelParameters:
    """Dimensionless parameters for qualitative local-regime exploration.

    The defaults are an interpretable scaffold rather than a calibrated biological
    system. Parameter ranges must be declared before biological regime frequencies
    or thresholds are interpreted.
    """

    baseline_outcross: float = 0.10
    attraction_gain: float = 1.20
    defence_pollinator_cost: float = 0.45
    assurance_gain: float = 0.70
    floral_damage_baseline: float = 0.20
    attraction_tracking: float = 1.10
    floral_defence_efficacy: float = 0.75
    attraction_cost: float = 0.22
    defence_cost: float = 0.24
    assurance_cost: float = 0.20
    attraction_defence_shared_cost: float = 0.10
    assurance_outcross_dilution: float = 0.10

    def __post_init__(self) -> None:
        for name, value in self.__dict__.items():
            if value < 0:
                raise ValueError(f"{name} must be non-negative")
        if self.floral_defence_efficacy > 1:
            raise ValueError("floral_defence_efficacy must lie in [0, 1]")
        if self.assurance_outcross_dilution > 1:
            raise ValueError("assurance_outcross_dilution must lie in [0, 1]")


@dataclass(frozen=True)
class FitnessBreakdown:
    """Channel-specific score bookkeeping for one phenotype and regime."""

    outcross_benefit: float
    assurance_benefit: float
    floral_damage_loss: float
    investment_cost: float

    @property
    def total(self) -> float:
        return (
            self.outcross_benefit
            + self.assurance_benefit
            - self.floral_damage_loss
            - self.investment_cost
        )


def fitness(
    architecture: Architecture,
    regime: InteractionRegime,
    parameters: ModelParameters = ModelParameters(),
) -> FitnessBreakdown:
    """Evaluate the qualitative score decomposition for the declared focal pair.

    ``P`` and ``H`` are reference-regime intensities held external to the focal
    trait effects.  Realised pollinator use and realised damage are generated by
    the trait-dependent terms below; treating those realised outcomes as ``P`` or
    ``H`` would double-count the focal trait effects.
    """

    a, d, r = architecture.attraction, architecture.defence, architecture.assurance
    p = regime.pollinator_service
    h = regime.floral_damage_pressure

    pollination_access = exp(-parameters.defence_pollinator_cost * d)
    outcross_benefit = (
        p
        * (parameters.baseline_outcross + parameters.attraction_gain * a)
        * pollination_access
        * (1.0 - parameters.assurance_outcross_dilution * r)
    )

    assurance_benefit = (1.0 - p) * parameters.assurance_gain * r

    floral_exposure = parameters.floral_damage_baseline + parameters.attraction_tracking * a
    floral_damage_loss = h * floral_exposure * (1.0 - parameters.floral_defence_efficacy * d)

    investment_cost = (
        parameters.attraction_cost * a * a
        + parameters.defence_cost * d * d
        + parameters.assurance_cost * r * r
        + parameters.attraction_defence_shared_cost * a * d
    )

    return FitnessBreakdown(
        outcross_benefit=outcross_benefit,
        assurance_benefit=assurance_benefit,
        floral_damage_loss=floral_damage_loss,
        investment_cost=investment_cost,
    )
