from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANUSCRIPT = ROOT / "manuscript" / "MANUSCRIPT_THEORETICAL_ECOLOGY.md"
CONCLUSION = '## 7. Conclusions\n\nThe identity \\(W_{AD}=\\rho-\\iota-\\kappa\\) is bookkeeping, not the main claim. The stronger result is one-sided: under non-negative joint-cost curvature, floral attraction-defence complementarity cannot occur outside the selectivity window in which antagonist relief exceeds pollinator interference. The declared 2,592-evaluation design contains no counterexample to that implication, while approximately 23% of in-window evaluations are substitutable, ruling out the converse as a universal criterion.\n\nPart II supplies a matching empirical Pattern rather than a validation of total \\(W_{AD}\\). The constituent pathways and switching architectures recur across independent systems. The floral-larceny synthesis shows that the antagonist-pressure gate is open on average and robust to influence and ingest choices, yet prediction intervals span both signs and the declared context axes explain little of the heterogeneity. The window can therefore open in nature, but its location is not yet predictable from the tested moderators. The within-study reward-mediated mechanism chain is not demonstrated.\n\nThe final unresolved quantity now has a precise role. Direct joint-cost curvature remains unmeasured in the strict evidence layer, and a sufficiently negative value is the only way the strongest one-sided bound can fail within the declared family. Its sign can be tested with a simple 2 × 2 allocation experiment, whereas estimating total \\(W_{AD}\\) still requires the much harder attraction × defence factorial with channel-specific and total-fitness outcomes.\n\nThe integrated result is thus a **one-sided mechanistic theorem plus a recurrent but context-dependent empirical Pattern**. What remains unknown — where the window lies in a new system and whether joint construction is synergistically cheap enough to break the bound — is no longer an unresolved link inside the argument. It is the explicit, falsifiable next experiment generated by the argument.'

def replace_section(text, start_heading, next_heading, replacement):
    start = text.index(start_heading + "\n")
    end = text.index(next_heading + "\n", start)
    return text[:start] + replacement.rstrip() + "\n\n" + text[end:]

def main():
    text = MANUSCRIPT.read_text(encoding="utf-8")
    text = replace_section(text, "## 7. Conclusions", "## Figure captions", CONCLUSION)
    MANUSCRIPT.write_text(text, encoding="utf-8")
    print("synchronized manuscript conclusion story")

if __name__ == "__main__":
    main()
